export type CategoryId =
  | "produce"
  | "bakery"
  | "dairy"
  | "butcher"
  | "pantry"
  | "drinks"

export type Product = {
  id: string
  name: string
  producer: string
  origin: string
  unit: string
  price: number
  category: CategoryId
  image: string
  tag?: "New" | "Seasonal" | "Last few" | "Best seller"
  note: string
}

export const categories: { id: CategoryId; label: string; blurb: string }[] = [
  { id: "produce", label: "Produce", blurb: "Picked within 24 hours" },
  { id: "bakery", label: "Bakery", blurb: "Baked before sunrise" },
  { id: "dairy", label: "Dairy & Eggs", blurb: "Small herd, raw milk" },
  { id: "butcher", label: "Butcher & Fish", blurb: "Whole-animal, day boat" },
  { id: "pantry", label: "Pantry", blurb: "Single origin staples" },
  { id: "drinks", label: "Drinks", blurb: "Pressed, never concentrate" },
]

export const products: Product[] = [
  {
    id: "cherry-tomatoes",
    name: "Vine Cherry Tomatoes",
    producer: "Ash Farm",
    origin: "Kent",
    unit: "400g punnet",
    price: 4.2,
    category: "produce",
    image: "/images/products/cherry-tomatoes.png",
    tag: "Seasonal",
    note: "Grown in soil, not water. Sugars concentrate in the last week on the vine.",
  },
  {
    id: "rainbow-chard",
    name: "Rainbow Chard",
    producer: "Marsh Market Garden",
    origin: "Somerset",
    unit: "Large bunch",
    price: 3.1,
    category: "produce",
    image: "/images/products/rainbow-chard.png",
    note: "Cut to order the morning your box is packed. Stems braise, leaves wilt.",
  },
  {
    id: "heirloom-apples",
    name: "Heirloom Apple Mix",
    producer: "Colby Orchard",
    origin: "Herefordshire",
    unit: "1.2kg",
    price: 6.5,
    category: "produce",
    image: "/images/products/heirloom-apples.png",
    tag: "Best seller",
    note: "Six old varieties in one crate — russet, pippin, and three we cannot pronounce.",
  },
  {
    id: "bell-peppers",
    name: "Sweet Bell Peppers",
    producer: "Glasshouse No. 4",
    origin: "Isle of Wight",
    unit: "3 peppers",
    price: 3.8,
    category: "produce",
    image: "/images/products/bell-peppers.png",
    note: "Ripened to full colour on the plant, which takes three weeks longer.",
  },
  {
    id: "romanesco",
    name: "Romanesco & Purple Cauliflower",
    producer: "Marsh Market Garden",
    origin: "Somerset",
    unit: "2 heads",
    price: 5.4,
    category: "produce",
    image: "/images/products/romanesco.png",
    tag: "Last few",
    note: "A fractal you can roast. Keeps its colour if you go hot and fast.",
  },
  {
    id: "sourdough-loaf",
    name: "Country Sourdough",
    producer: "Bench Bakery",
    origin: "London Fields",
    unit: "900g loaf",
    price: 5.5,
    category: "bakery",
    image: "/images/products/sourdough-loaf.png",
    tag: "Best seller",
    note: "Three flours, a 36-hour cold ferment, and one baker who refuses to rush it.",
  },
  {
    id: "rye-loaf",
    name: "Dark Rye Loaf",
    producer: "Bench Bakery",
    origin: "London Fields",
    unit: "750g loaf",
    price: 5.9,
    category: "bakery",
    image: "/images/products/rye-loaf.png",
    note: "Dense, malty, and better on day three. Cut it thin.",
  },
  {
    id: "croissants",
    name: "Butter Croissants",
    producer: "Bench Bakery",
    origin: "London Fields",
    unit: "Pack of 4",
    price: 7.2,
    category: "bakery",
    image: "/images/products/croissants.png",
    tag: "New",
    note: "Laminated with the same cultured butter we sell two rows down.",
  },
  {
    id: "duck-eggs",
    name: "Pasture Duck Eggs",
    producer: "Willow Yard",
    origin: "Suffolk",
    unit: "Box of 6",
    price: 4.6,
    category: "dairy",
    image: "/images/products/duck-eggs.png",
    note: "Richer yolks than hen eggs. Unbeatable in a custard or a fried rice.",
  },
  {
    id: "cultured-butter",
    name: "Cultured Butter",
    producer: "Hollow Dairy",
    origin: "Devon",
    unit: "250g block",
    price: 5.8,
    category: "dairy",
    image: "/images/products/cultured-butter.png",
    tag: "Best seller",
    note: "Cream soured for 18 hours before churning. Salted with Maldon flakes.",
  },
  {
    id: "aged-cheese",
    name: "18-Month Alpine Cheese",
    producer: "Fell Creamery",
    origin: "Cumbria",
    unit: "220g wedge",
    price: 9.4,
    category: "dairy",
    image: "/images/products/aged-cheese.png",
    note: "Raw milk, brushed rind, and crystals that crunch. Cut from a full wheel weekly.",
  },
  {
    id: "dry-aged-ribeye",
    name: "Dry-Aged Ribeye",
    producer: "Hart & Sons",
    origin: "Yorkshire",
    unit: "350g steak",
    price: 16.5,
    category: "butcher",
    image: "/images/products/dry-aged-ribeye.png",
    tag: "Last few",
    note: "Grass-fed, hung 35 days on the bone. Rest it as long as you cook it.",
  },
  {
    id: "free-range-chicken",
    name: "Free-Range Whole Chicken",
    producer: "Willow Yard",
    origin: "Suffolk",
    unit: "1.6kg bird",
    price: 13.9,
    category: "butcher",
    image: "/images/products/free-range-chicken.png",
    note: "Slow-grown to 81 days. Enough carcass for a proper stock afterwards.",
  },
  {
    id: "sea-bass",
    name: "Day Boat Sea Bass",
    producer: "Kittiwake",
    origin: "Cornwall",
    unit: "2 fillets",
    price: 11.2,
    category: "butcher",
    image: "/images/products/sea-bass.png",
    tag: "Seasonal",
    note: "Line caught yesterday, filleted this morning, scored for the pan.",
  },
  {
    id: "olive-oil",
    name: "First Press Olive Oil",
    producer: "Casa Verde",
    origin: "Jaén",
    unit: "500ml",
    price: 14.8,
    category: "pantry",
    image: "/images/products/olive-oil.png",
    tag: "Best seller",
    note: "Single estate picoal, milled within four hours of picking. Peppery finish.",
  },
  {
    id: "spaghetti",
    name: "Bronze-Cut Spaghetti",
    producer: "Molino Sesto",
    origin: "Gragnano",
    unit: "500g",
    price: 4.4,
    category: "pantry",
    image: "/images/products/spaghetti.png",
    note: "Rough surface, slow dried for 40 hours. Sauce actually sticks to it.",
  },
  {
    id: "wild-honey",
    name: "Wildflower Honey",
    producer: "Ninefold Apiary",
    origin: "Dorset",
    unit: "340g jar",
    price: 8.6,
    category: "pantry",
    image: "/images/products/wild-honey.png",
    note: "Unfiltered and unheated, so it sets. That is the honey working properly.",
  },
  {
    id: "coffee-beans",
    name: "Filter Coffee Beans",
    producer: "Kiln Roasters",
    origin: "Huila",
    unit: "250g whole bean",
    price: 12.5,
    category: "drinks",
    image: "/images/products/coffee-beans.png",
    tag: "New",
    note: "Washed caturra roasted last Tuesday. Stone fruit, cane sugar, no bitterness.",
  },
  {
    id: "orange-juice",
    name: "Cold-Pressed Orange Juice",
    producer: "Grove Kitchen",
    origin: "Valencia",
    unit: "750ml",
    price: 5.2,
    category: "drinks",
    image: "/images/products/orange-juice.png",
    note: "Fourteen oranges per bottle. Nothing added, not even water.",
  },
  {
    id: "elderflower-presse",
    name: "Elderflower Pressé",
    producer: "Hedgerow Co.",
    origin: "Wiltshire",
    unit: "750ml",
    price: 4.9,
    category: "drinks",
    image: "/images/products/elderflower-presse.png",
    tag: "Seasonal",
    note: "Foraged blossom steeped for two days. Dry, floral, barely sweet.",
  },
]

export function formatPrice(value: number) {
  return `£${value.toFixed(2)}`
}
